%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\User\OneDrive\Documents\M1\Quantitative Macroeconomics\Problem sets\Week_2\CLVMNACSCAB1GQNO.csv
%
% Auto-generated by MATLAB on 27-Oct-2022 10:39:55

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [12, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["DATE", "DATA"];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "DATA", "TrimNonNumeric", true);
opts = setvaropts(opts, "DATA", "ThousandsSeparator", ",");

% Import the data
NorwayGDP = readtable("C:\Users\User\OneDrive\Documents\M1\Quantitative Macroeconomics\Problem sets\Week_2\CLVMNACSCAB1GQNO.csv", opts);


%% Clear temporary variables
clear opts

NorwayGDP.DATE.Format = "yyyy-QQQ";